# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import naboj_zona.struct_wiki.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('struct_wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='secret',
            field=models.CharField(default=naboj_zona.struct_wiki.helpers.generate_domain_secret, max_length=24),
        ),
        migrations.AlterField(
            model_name='articleholder',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='struct_wiki.ArticleTag'),
        ),
    ]
