# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        ('struct_wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHolder',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='holder', serialize=False, to='wiki.Article')),
                ('recursive', models.BooleanField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_holders', to='struct_wiki.Domain')),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('admin', 'Admin'), ('member', 'Member')], max_length=8),
        ),
    ]
