# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struct_wiki', '0002_auto_20160904_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=8),
        ),
    ]
