# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struct_wiki', '0003_auto_20160909_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleholder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleholder',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holder', to='wiki.Article'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer'), ('member', 'Member')], max_length=8),
        ),
    ]
