# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struct_wiki', '0004_auto_20160909_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('viewer', 'Viewer')], max_length=8),
        ),
        migrations.AddField(
            model_name='articleholder',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='struct_wiki.ArticleTag'),
        ),
    ]
